services:
  frontend:
    build: 
      context: ./source
      dockerfile: ./frontend/Dockerfile
    ports: 
      - "80:80"
  server:
    build: ./source/backend
    ports:
      - "3000:3000"
      - "3001:3001"
  redis:
    image: "redis/redis-stack:7.2.0-v0"
    ports:
      - "6379:6379"
      - "8001:8001"
  mongo:
    image: "mongodb/mongodb-community-server:6.0-ubi8"
    ports:
      - "27017:27017"